##We can initialize numpy arrays from nested Python lists, and access elements using square brackets

In [1]:
import numpy as np

a = np.array([1, 2, 3])  # Create a rank 1 array
print type(a)            # Prints "<type 'numpy.ndarray'>"
print a.shape            # Prints "(3,)"
print a[0], a[1], a[2]   # Prints "1 2 3"
a[0] = 5                 # Change an element of the array
print a                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print b.shape                     # Prints "(2, 3)"
print b[0, 0], b[0, 1], b[1, 0]   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [9]:
x = np.array([1,4,7])
print x

[1 4 7]


In [19]:
y = np.array([range(1,7,1),range(2,8,1)])
print y
print y.shape

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
(2, 6)


In [20]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print z
print z.shape
print z[2,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


##Numpy also provides many functions to create arrays

In [30]:
a = np.zeros((2,2))  # Create an array of all zeros
print a              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"

b = np.ones((1,2))   # Create an array of all ones
print b              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7) # Create a constant array
print c               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

d = np.eye(2)        # Create a 2x2 identity matrix
print d              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
print e                     # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.57043017  0.25088702]
 [ 0.56067861  0.79123016]]


In [21]:
a = np.zeros((3,3))
print a
print a.shape

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
(3, 3)


In [23]:
b = 4*np.ones((2,2))
print b
print b.shape

[[ 4.  4.]
 [ 4.  4.]]
(2, 2)


In [25]:
c = np.full((2,2),4)
print c
print c.shape

[[ 4.  4.]
 [ 4.  4.]]
(2, 2)


In [26]:
d = np.eye(4)
print d

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [29]:
e = np.random.random((7,6))
print e

[[ 0.15983826  0.63819441  0.78692874  0.79455057  0.05153629  0.10763788]
 [ 0.04875354  0.23595801  0.92630831  0.81884992  0.91547805  0.00823285]
 [ 0.43067953  0.66840405  0.86994747  0.10837279  0.37564369  0.91901489]
 [ 0.79499517  0.73036975  0.05050371  0.45251329  0.46963539  0.31760417]
 [ 0.62933432  0.99509119  0.51758946  0.01382193  0.50299028  0.58171542]
 [ 0.95963559  0.06771518  0.04012151  0.71324694  0.56930055  0.13732529]
 [ 0.8031591   0.03862216  0.97835252  0.88662457  0.68307477  0.00776691]]


##Array indexing

###Numpy offers several ways to index into arrays.

###Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [36]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print a
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2,1:3]
print b
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print b[1,1]
print a[1,2]
b[1,1] = 11
print b[1,1]
print a[1,2]
print b
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
7
7
11
11
[[ 2  3]
 [ 6 11]]
[[ 1  2  3  4]
 [ 5  6 11  8]
 [ 9 10 11 12]]


###You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [38]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1,:]
print row_r1, row_r1.shape
row_r2 = a[1:2,:]
print row_r2, row_r2.shape

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [39]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:,1]
print col_r1, col_r1.shape
col_r2 = a[:,1:2]
print col_r2, col_r2.shape

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


##Integer array indexing 

####When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example

In [48]:
a = np.array([[1,2],[3,4],[5,6]])
print a
print
print 'size', a.size
print 'shape', a.shape

[[1 2]
 [3 4]
 [5 6]]

size 6
shape (3, 2)


In [42]:
print a[[0,1,2],[1,0,1]]
# The above example of integer array indexing is equivalent to this:
print np.array([a[0,1], a[1,0], a[2,1]])

[2 3 6]
[2 3 6]


In [52]:
print a
print a[[0,0],[1,1]]
# Equivalent to the previous integer array indexing example
print np.array([a[0, 1], a[0, 1]])  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[2 2]
[2 2]


##Boolean array indexing 
###Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example

In [55]:
print a
bool_idx = a>2
print bool_idx
print a[bool_idx]
print a[a>2]

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


##Array Math

In [66]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print x
print y
print x+y
print np.add(x,y)
print x - y
print np.subtract(x, y)
print x*y
print np.multiply(x,y)
print np.divide(y,x)
print np.sqrt(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[5 3]
 [2 2]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [67]:
x = np.array([[1,2],[3,4]], dtype = np.float)
y = np.array([[5,6],[7,8]], dtype = np.float)
print x
print y
print x+y
print np.add(y,x)
print y - x
print np.subtract(y,x)
print np.divide(y,x)
print y/x
print np.sqrt(x)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]
[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[ 4.  4.]
 [ 4.  4.]]
[[ 4.  4.]
 [ 4.  4.]]
[[ 5.          3.        ]
 [ 2.33333333  2.        ]]
[[ 5.          3.        ]
 [ 2.33333333  2.        ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [70]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4],[5,6]])
print x
print y
print x*x
print y*y
print np.multiply(x,x)
print np.multiply(y,y)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]


####Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [72]:
print x.dot(y)

[[22 28]
 [49 64]]


In [73]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print x*x
print x.dot(x)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [74]:
print np.dot(x,y)
print x.dot(y)
print np.dot(y,x)
print y.dot(x)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[23 34]
 [31 46]]


###Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum

In [76]:
x = np.array([[1,2],[3,4]])
print x

[[1 2]
 [3 4]]


In [78]:
print np.sum(x)
print np.sum(x, axis = 0) # Computes the sum of each column
print np.sum(x, axis = 1) # Computes the sum of each row

10
[4 6]
[3 7]


###Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object

In [79]:
x = np.array([[1,2,3],[4,5,6]])
print x
print x.T

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [82]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print v
print v.T

[1 2 3]
[1 2 3]


##Broadcasting
####Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

####For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [90]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)
print x
print y
print v
print 
print 
for i in xrange(4):
    y[i,:] = x[i,:] + v
print y

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [92]:
print x
print np.empty_like(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [95]:
print v
vv = np.tile(v,(4,1)) # Stack 4 copies of v on top of each other
print vv
y = x + vv
print y

[1 0 1]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


###Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [98]:
print x, x.shape
print v, v.shape
print x + v

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 1] (3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

###Functions that support broadcasting are known as universal functions. Here are some applications of broadcasting:

In [99]:
v = np.array([1,2,3])
w = np.array([4,5])
print np.reshape(v,(3,1))*w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [100]:
x = np.array([[1,2,3], [4,5,6]])
print x+v

[[2 4 6]
 [5 7 9]]


In [101]:
print x

[[1 2 3]
 [4 5 6]]


In [103]:
print x
print x.T
print w
print x.T + w
print (x.T + w).T

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[4 5]
[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [104]:
print x
print w
print x + np.reshape(w,(2,1))

[[1 2 3]
 [4 5 6]]
[4 5]
[[ 5  6  7]
 [ 9 10 11]]


In [106]:
print x
print x*2

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
